---
name: Install uv, Python, and project dependencies
description: Install uv, Python, and project dependencies using cached uv and Python installations

inputs:
  python-version:
    description: >
      Version range or exact version of a Python version to use, using SemVer's version range syntax.
    required: false
    default: "3.12"

runs:
  using: composite
  steps:
    - name: Setup uv with cache
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev

    - name: Debug Python version
      shell: bash
      run: |
        echo "Input python-version: ${{ inputs.python-version }}"
        echo "Python version: $(python --version)"
        echo "Python location: $(which python)"
        echo "uv Python version: $(uv python --version)"

    - name: Minimize uv cache
      shell: bash
      run: uv cache prune --ci

    - name: Install SQLite
      shell: bash
      run: sudo apt install -y sqlite3

    # ----------------------------------------------
    #    copy config file to runner
    # ----------------------------------------------
    - name: Create empty configuration file
      shell: bash
      run: mkdir -p /home/runner/.config/halp && cp ./src/halper/default_config.toml /home/runner/.config/halp/config.toml
