---
codecov:
    token: secret:v2::E8rKV+JfSEwQ80vahssqUns92P80jJsfVNLwLeFZm2am8aBkg+8t6oXr6r4TY7CN3eMg3ZInQtUbktmlDw/yzyAe+zbh/N+euPHNenRQn90=
coverage:
    status:
        project:
            default:
                target: 50% # the required coverage value
                threshold: 5% # the leniency in hitting the target
        patch:
            default:
                target: 50%
                threshold: 5%
    ignore:
        - tests/

comment:
    layout: "reach, diff, flags, files" # Remove items here to change the format
    require_changes: true
