---
name: "Automated Tests"

on:
    workflow_dispatch:
    push:
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "uv.lock"
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "uv.lock"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-python-code:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: lint with ruff
              shell: bash
              run: uv run ruff check --no-fix src/

            - name: Run tests
              shell: bash
              run: uv run pytest tests/

    upload-coverage:
        runs-on: ubuntu-latest
        needs: test-python-code
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.12"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: Run tests with pytest
              run: |
                  uv run coverage run
                  uv run coverage report
                  uv run coverage xml

            # ----------------------------------------------
            #             upload coverage stats
            # ----------------------------------------------
            - name: Upload coverage
              uses: codecov/codecov-action@v4
              with:
                  files: reports/coverage.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
