---
name: Publish to PyPi
on:
    workflow_dispatch:
    release:
        types:
            - published

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish-to-pypi:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tasks
            # ----------------------------------------------
            - name: Run tests
              shell: bash
              run: uv run pytest tests/

            - name: Build the package
              shell: bash
              run: uvx --from build pyproject-build --installer uv

            - name: Upload to PyPi
              shell: bash
              run: uvx twine upload dist/*
