---
name: "Tests"

on:
    workflow_dispatch:
    push:
        paths:
            - ".github/workflows/test.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "uv.lock"
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - ".github/workflows/test.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "uv.lock"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    run-tests:
        if: ${{ !contains(github.event.head_commit.message, 'bump(release)') }}
        uses: ./.github/workflows/reusable-tests.yml
        secrets: inherit
        with:
            run-coverage: true
